version: '3.9'
services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - 6379:6379
  app:
    build: .
    command: flask run -p 5000 -h 0.0.0.0
    ports:
      - 5000:5000
    depends_on:
      - redis